version: '3'
services:
  redis:
    image: "redis:alpine"
  wsgi:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
    depends_on:
      - redis
    environment:
      - DEV_ENV=True