openapi: 3.0.0

servers:
  - description: Development
    url: http://0.0.0.0:8080
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/akh11k/flask-template/1.0.0

info:
  version: 1.0.0
  title: A flask template
  contact:
    name: akh11k
    url: https://github.com/akh11k/
    email: akh11k@protonmail.com

tags:
  - name: RQ
    description: RQ operations

components:
  responses:
    ResourceNotFound:
      description: Requested resource is not found on the server
      content:
        application/json:
          schema:
            type: object
            properties:
              details:
                type: string

  schemas:
    TaskInfo:
      type: object
      properties:
        status:
          type: string
          enum: [queued, started, finished, failed]
        result:
          type: object
        progress:
          type: object

paths:
  /isActive:
    get:
      summary: Application health check
      operationId: routes.health.is_active
      responses:
        200:
          description: Active
          content:
            text/plain:
              schema:
                type: boolean

  /wait/job:
    get:
      summary: Test progress job
      operationId: routes.health.wait
      parameters:
        - in: query
          name: t
          schema:
            type: integer
          required: true
      responses:
        200:
          description: The job_id
          content:
            application/json:
              schema:
                type: object
                properties:
                  job_id:
                    type: string
                    example: qlejsfkoe395jfh-13kjiemdjanj-3jmni09njnnk-dsfadmkj

  /tasks/{task_id}:
    get:
      tags:
        - RQ
      summary: Get the rq task
      operationId: utils.rq.get_task_info
      parameters:
        - in: path
          name: task_id
          schema:
            type: string
          required: true
      responses:
        200:
          description: The task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskInfo'
        404:
          $ref: '#/components/responses/ResourceNotFound'
